# Deploy 3 Azure Function Apps with Dependency Injection

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'my-subscription'
  # Function app names
  functionApp1: 'my-function-app-1'
  functionApp2: 'my-function-app-2'
  functionApp3: 'my-function-app-3'

stages:
- stage: Deploy
  displayName: Deploy Function Apps
  jobs:
  - job: DeployFunctionApps
    displayName: Deploy Function Apps
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: 'inlineScript'
        inlineScript: |
          az functionapp config appsettings set --name $(functionApp1) --resource-group my-resource-group --settings 'MySetting1=Value1'
          az functionapp config appsettings set --name $(functionApp2) --resource-group my-resource-group --settings 'MySetting2=Value2'
          az functionapp config appsettings set --name $(functionApp3) --resource-group my-resource-group --settings 'MySetting3=Value3'
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'functionAppLinux'
        appName: $(functionApp1)
        package: '$(Pipeline.Workspace)/$(functionApp1)/$(Build.BuildId).zip'
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'functionAppLinux'
        appName: $(functionApp2)
        package: '$(Pipeline.Workspace)/$(functionApp2)/$(Build.BuildId).zip'
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'functionAppLinux'
        appName: $(functionApp3)
        package: '$(Pipeline.Workspace)/$(functionApp3)/$(Build.BuildId).zip'
